set(vtkCommonCore_LOADED 1)
set(vtkCommonCore_DEPENDS "vtksys")
set(vtkCommonCore_LIBRARIES "vtkCommonCore")
set(vtkCommonCore_INCLUDE_DIRS "/home/tim/CMU/SunTracker/IMU/VTK-6.2.0/Common/Core")
set(vtkCommonCore_LIBRARY_DIRS "")
set(vtkCommonCore_RUNTIME_LIBRARY_DIRS "/home/tim/CMU/SunTracker/IMU/VTK-6.2.0/lib")
set(vtkCommonCore_WRAP_HIERARCHY_FILE "")
set(VTK_DEBUG_LEAKS "OFF")
set(VTK_USE_64BIT_IDS "ON")
set(VTK_ALL_NEW_OBJECT_FACTORY "OFF")

